apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-talent-eval
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-talent-eval.streamsoft.cn
      secretName: streamsoft-hk-tls
  rules:
    - host: ai-talent-eval.streamsoft.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-talent-eval
                port:
                  number: 80
